DROP TABLE Exclusion IF EXISTS;

CREATE TABLE Exclusion (  
	id   INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,  
	host VARCHAR(100),
	excluded_since DATE,
	excluded_till DATE
);

CREATE INDEX Exclusion_website ON Exclusion (host)